---
version: "3.3"

services:
  nodeapp:
   image: nodeapp
   ports:
    - "51005:51005"
   depends_on:
    - mysql
    - mongo
   volumes: 
    - nodeapp:/app/
   container_name: web

  mysql: 
   image: mysql 
   environment: 
    MYSQL_ROOT_PASSWORD: password
   volumes: 
    - mysql:/var/lib/mysql/
   container_name: mysql

  mongo:
    image: mongo
    ports:
    - "27017:27017"
    volumes: 
     - mongo:/data/db/
    depends_on: 
     - mysql
    container_name: mongo
volumes: 
 nodeapp:
 mysql:  
 mongo:
